### ISSUE TITLE
Properly namespace the project

### ISSUE THREAD

**Issue by bhb** [figly/repl-tools#4]
Instead of `repl-tools`, it should be namespaced to figly. Possibly options.
- `com.figly/repl-tools` (examples: [1](https://clojars.org/com.vitalreactor/probe), [2](https://clojars.org/com.rpl/specter))
- `figly/repl-tools` (examples: [1](https://clojars.org/prismatic/schema), [2](https://clojars.org/circleci/lein-daemon))

Thoughts?

**Comment by abram** [comment]
I prefer the simpler version without the reverse-dns naming.

**Comment by cldwalker** [comment]
I don't have a strong preference though if we do it here, it would be nice to do it consistently across projects

**Comment by bhb** [comment]
I prefer `figly/repl-tools` as well. Let's do that.

@cldwalker Can you expand a bit on that? The main reason I want to namespace here is that this will be public. Can you talk a little about the benefits of namespacing to "figly" for private projects?

**Comment by cldwalker** [comment]
Consistency is the main benefit. leiningen converts namespaces to maven groups. Feels strange to have different maven groups for the same org

**Comment by bhb** [comment]
@cldwalker Cool. I'm unfamiliar with maven groups (and how lein deals with them) so that's good to know. I don't see a downside so might as well namespace all the projects as per your suggestion.

**Comment by bhb** [comment]
Closing since we're not using this project anymore.
